# Generated by Django 4.0.3 on 2022-03-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_reply_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='extra',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
