# Generated by Django 4.0.3 on 2022-03-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='canView',
            field=models.CharField(default='No', max_length=3),
        ),
    ]
