# Generated by Django 4.0.2 on 2022-02-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_comments_user_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='posted_by',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
