# Generated by Django 4.0.2 on 2022-02-21 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_profile_f1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='f1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
    ]
