# Generated by Django 4.0.2 on 2022-02-21 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
    ]
