# Generated by Django 4.0.2 on 2022-02-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_image_name_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(null=True, upload_to='test/'),
        ),
    ]
