# Generated by Django 4.0.2 on 2022-02-21 20:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0013_alter_profile_picture_friends'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friends',
            new_name='Circle',
        ),
    ]
