# Generated by Django 4.0.2 on 2022-02-21 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_alter_test_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
