# Generated by Django 4.0.2 on 2022-02-21 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='test',
            new_name='work',
        ),
    ]
