# Generated by Django 4.0.2 on 2022-02-21 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_rename_test_attrib'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attrib',
        ),
    ]
