# Generated by Django 4.0.2 on 2022-02-21 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_delete_attrib'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Circle',
        ),
    ]
