# Generated by Django 4.0.2 on 2022-02-22 00:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0025_circle_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='sent_requests',
            field=models.ManyToManyField(related_name='sent_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
